# Generated by Django 4.0.5 on 2022-07-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=45)),
                ('industry_id', models.IntegerField(default=3)),
            ],
            options={
                'db_table': 'player',
                'managed': False,
            },
        ),
    ]
