# Generated by Django 4.0.5 on 2022-07-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0002_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('file', models.FileField(blank=True, upload_to='uploads/')),
            ],
            options={
                'db_table': 'icon_model',
                'managed': True,
            },
        ),
    ]
