# Generated by Django 4.0.5 on 2022-07-31 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0004_reportpagesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPlayerModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginAPI.player')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginAPI.reportmodel')),
            ],
            options={
                'db_table': 'ReportPlayerModel',
                'managed': True,
            },
        ),
    ]
