# Generated by Django 4.0.5 on 2022-08-11 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0005_reportplayermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientmodel',
            old_name='login_mode',
            new_name='wildcard_mode',
        ),
        migrations.AddField(
            model_name='user',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LoginAPI.clientmodel'),
            preserve_default=False,
        ),
    ]
