# Generated by Django 4.0.5 on 2022-08-11 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0006_rename_login_mode_clientmodel_wildcard_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportaccessmodel',
            name='email',
        ),
    ]
