# Generated by Django 4.0.5 on 2022-10-13 11:25

import LoginAPI.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0008_user_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportaccessmodel',
            name='end_date',
            field=models.DateField(blank=True, default=LoginAPI.models.get_deadline, null=True),
        ),
        migrations.AlterField(
            model_name='reportaccessmodel',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
