# Generated by Django 4.0.5 on 2023-01-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0010_reportaccessmodel_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=200)),
                ('reports', models.ManyToManyField(to='LoginAPI.reportmodel')),
            ],
            options={
                'db_table': 'tag_model',
                'managed': True,
            },
        ),
    ]
