# Generated by Django 4.0.5 on 2023-01-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0011_tagmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPopupModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.IntegerField(default=None)),
                ('email', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'UserPopup_model',
                'managed': True,
            },
        ),
    ]
