# Generated by Django 4.0.5 on 2023-01-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0012_userpopupmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpopupmodel',
            name='mobile',
        ),
        migrations.AddField(
            model_name='userpopupmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
