# Generated by Django 4.0.5 on 2023-01-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0013_remove_userpopupmodel_mobile_userpopupmodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpopupmodel',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userpopupmodel',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpopupmodel',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
