# Generated by Django 4.0.5 on 2023-02-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0014_alter_userpopupmodel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpagesmodel',
            name='url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
