# Generated by Django 4.0.5 on 2023-02-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0015_reportpagesmodel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpagesmodel',
            name='powerbi_report_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
