# Generated by Django 4.0.5 on 2023-02-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0016_reportpagesmodel_powerbi_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpagesmodel',
            name='report_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
