# Generated by Django 4.0.5 on 2023-02-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0017_reportpagesmodel_report_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpagesmodel',
            name='same_page',
            field=models.BooleanField(default=False),
        ),
    ]
