# Generated by Django 4.0.5 on 2023-02-07 10:53

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0018_reportpagesmodel_same_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewReportModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=100)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='LoginAPI.newreportmodel')),
            ],
            options={
                'db_table': 'new_report_model',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NewReportPagesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('page_name', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('url', models.TextField(blank=True, default=None, null=True)),
                ('powerbi_report_id', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('report_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('same_page', models.BooleanField(default=False)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginAPI.newreportmodel')),
            ],
            options={
                'db_table': 'new_report_pages',
                'managed': True,
            },
        ),
    ]
