# Generated by Django 4.0.5 on 2023-02-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0021_remove_reportpagesmodel_embed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newreportpagesmodel',
            name='info',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
