# Generated by Django 4.0.5 on 2023-02-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0023_remove_newreportpagesmodel_info_newreportmodel_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='newreportmodel',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
    ]
