# Generated by Django 4.0.5 on 2023-02-24 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0024_newreportmodel_finalized'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCurrencyModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(blank=True, default='USD', max_length=200, null=True)),
                ('email', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginAPI.newreportmodel')),
            ],
        ),
    ]
