# Generated by Django 4.0.5 on 2023-02-24 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0025_usercurrencymodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercurrencymodel',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='usercurrencymodel',
            table='user_currency_model',
        ),
    ]
