# Generated by Django 4.0.5 on 2023-02-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0026_alter_usercurrencymodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercurrencymodel',
            name='report',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
