# Generated by Django 4.0.5 on 2023-02-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0027_alter_usercurrencymodel_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercurrencymodel',
            name='year',
            field=models.CharField(blank=True, default='FY', max_length=200, null=True),
        ),
    ]
