# Generated by Django 4.0.5 on 2023-03-01 09:38

import LoginAPI.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0029_newreportaccessmodel_newreportpageaccessmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='newreportaccessmodel',
            name='end_date',
            field=models.DateField(blank=True, default=LoginAPI.models.get_deadline, null=True),
        ),
        migrations.AddField(
            model_name='newreportaccessmodel',
            name='players',
            field=models.ManyToManyField(to='LoginAPI.player'),
        ),
        migrations.AddField(
            model_name='newreportaccessmodel',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
