# Generated by Django 4.0.5 on 2023-03-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0030_newreportaccessmodel_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newreportaccessmodel',
            name='report_pages',
            field=models.ManyToManyField(to='LoginAPI.newreportpagesmodel'),
        ),
    ]
