# Generated by Django 4.0.5 on 2023-03-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0031_newreportaccessmodel_report_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newreportaccessmodel',
            name='players',
            field=models.ManyToManyField(blank=True, to='LoginAPI.player'),
        ),
        migrations.AlterField(
            model_name='newreportaccessmodel',
            name='report_pages',
            field=models.ManyToManyField(blank=True, to='LoginAPI.newreportpagesmodel'),
        ),
    ]
