# Generated by Django 4.0.5 on 2023-03-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0035_newreportmodel_node_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydomainmodel',
            name='otp_access',
            field=models.BooleanField(default=False),
        ),
    ]
