# Generated by Django 4.0.5 on 2023-03-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0038_remove_companydomainmodel_otp_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newreportmodel',
            name='filter_value',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
