# Generated by Django 4.0.5 on 2023-03-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0039_newreportmodel_filter_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newreportmodel',
            name='filter',
            field=models.CharField(blank=True, choices=[('categories', 'categories'), ('industry', 'industry'), ('1', 'player')], default=None, max_length=200, null=True),
        ),
    ]
