# Generated by Django 4.0.5 on 2023-04-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0041_newreportpagesmodel_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender_male',
            field=models.BooleanField(default=True),
        ),
    ]
