# Generated by Django 4.0.5 on 2023-04-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0042_user_gender_male'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender_male',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
