# Generated by Django 4.0.5 on 2023-04-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0043_alter_user_gender_male'),
    ]

    operations = [
        migrations.AddField(
            model_name='newreportmodel',
            name='free',
            field=models.BooleanField(default=False),
        ),
    ]
