# Generated by Django 4.0.5 on 2023-04-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0044_newreportmodel_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='newreportmodel',
            name='has_link',
            field=models.BooleanField(default=True),
        ),
    ]
