# Generated by Django 4.0.5 on 2023-04-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0045_newreportmodel_has_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='newreportpagesmodel',
            name='component',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newreportpagesmodel',
            name='component_variable',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='newreportpagesmodel',
            name='page_type',
            field=models.CharField(blank=True, choices=[('powerbi', 'powerbi'), ('httpsAddress', 'httpAddress'), ('component', 'component')], default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newreportmodel',
            name='filter',
            field=models.CharField(blank=True, choices=[('sector', 'sector'), ('categories', 'categories'), ('industry', 'industry'), ('1', 'player')], default=None, max_length=200, null=True),
        ),
    ]
