# Generated by Django 4.0.5 on 2023-05-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0046_newreportpagesmodel_component_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'PackageModel',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='newreportmodel',
            name='filter',
            field=models.CharField(blank=True, choices=[('sector', 'sector'), ('categories', 'categories'), ('industry', 'industry'), ('1', 'player'), ('medical', 'medical')], default=None, max_length=200, null=True),
        ),
    ]
