# Generated by Django 4.0.5 on 2023-05-12 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0047_packagemodel_alter_newreportmodel_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='package',
            field=models.ManyToManyField(blank=True, null=True, to='LoginAPI.packagemodel'),
        ),
        migrations.AddField(
            model_name='newreportaccessmodel',
            name='package_id',
            field=models.ManyToManyField(blank=True, null=True, to='LoginAPI.packagemodel'),
        ),
        migrations.AlterField(
            model_name='newreportaccessmodel',
            name='client_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LoginAPI.clientmodel'),
        ),
    ]
