# Generated by Django 4.0.5 on 2023-05-15 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0048_clientmodel_package_newreportaccessmodel_package_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newreportaccessmodel',
            name='package_id',
        ),
        migrations.AddField(
            model_name='newreportaccessmodel',
            name='package_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LoginAPI.packagemodel'),
        ),
    ]
