# Generated by Django 4.0.5 on 2023-05-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0049_remove_newreportaccessmodel_package_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newreportpagesmodel',
            name='excel_access',
            field=models.BooleanField(default=False),
        ),
    ]
